/**
 * The platform default entity/relation extraction template shown in the
 * Platform Graph → Schema tab. Users can edit and persist their own version
 * (see routes/graph-template.ts); "Reset to default" restores this object.
 *
 * Shape: entry name -> { type: "actor" | "feature" | "relation", tokens: [] }.
 */
export const DEFAULT_EXTRACTION_TEMPLATE = {
  compound: {
    type: "actor",
    tokens: [
      "compound",
      "molecule",
      "inhibitor",
      "tbi",
      "tbp",
      "tbi-xxxx",
      "tbp-xxxx",
      "drug candidate",
      "synthesized compound",
      "virtual compound",
    ],
  },
  shp2: {
    type: "actor",
    tokens: [
      "shp2",
      "ptpn11",
      "src homology region 2-containing protein tyrosine phosphatase 2",
      "shp-2",
      "protein tyrosine phosphatase shp2",
    ],
  },
  ptp1b: {
    type: "actor",
    tokens: [
      "ptp1b",
      "protein tyrosine phosphatase 1b",
      "ptpn1",
      "selectivity counter-target",
    ],
  },
  phosphatase_panel: {
    type: "actor",
    tokens: [
      "phosphatase panel",
      "phosphatase selectivity panel",
      "counter-screen panel",
      "ptpase panel",
    ],
  },
  assay: {
    type: "actor",
    tokens: [
      "assay",
      "biochemical assay",
      "cellular assay",
      "biophysical assay",
      "admet assay",
      "spr assay",
      "thermal shift assay",
      "caco-2",
      "hlm",
      "cyp inhibition",
      "ic50 assay",
      "ki assay",
      "cell-based assay",
    ],
  },
  ml_model: {
    type: "actor",
    tokens: [
      "ml model",
      "qsar model",
      "machine learning model",
      "predictive model",
      "glide",
      "mc-mmgbsa",
      "docking model",
      "indazole qsar model",
      "admet prediction model",
    ],
  },
  cell_line: {
    type: "actor",
    tokens: [
      "cell line",
      "ba/f3",
      "mapk-driven cell line",
      "tumor cell line",
      "cancer cell line",
    ],
  },
  structural_context: {
    type: "actor",
    tokens: [
      "structural context",
      "binding pocket",
      "dfg-out conformation",
      "allosteric pocket",
      "tunnel site",
      "catalytic site",
      "sh2-domain interface",
      "protein conformation",
    ],
  },
  chemotype: {
    type: "feature",
    tokens: [
      "chemotype",
      "scaffold",
      "chemotype class",
      "indazole",
      "pyrazine",
      "aminopyridine",
      "indazole-based core",
      "pyrazine-linked scaffold",
      "aminopyridine series",
    ],
  },
  tier: {
    type: "feature",
    tokens: [
      "tier",
      "tier 1",
      "tier 2",
      "tier 3",
      "routing tier",
      "prioritization tier",
      "advancement tier",
    ],
  },
  cycle: {
    type: "feature",
    tokens: [
      "cycle",
      "design-make-test-analyze cycle",
      "dmta cycle",
      "iteration",
      "cycle 1",
      "cycle 2",
      "cycle 3",
      "campaign cycle",
    ],
  },
  assay_measurement: {
    type: "feature",
    tokens: [
      "ic50",
      "ki",
      "pic50",
      "kd",
      "delta tm",
      "spr kd",
      "hlm t1/2",
      "solubility",
      "permeability",
      "measured value",
      "binding affinity",
      "potency",
      "metabolic stability",
      "confidence score",
    ],
  },
  inhibits: {
    type: "relation",
    tokens: [
      "inhibits",
      "inhibit",
      "inhibition",
      "enzymatic inhibition",
      "suppresses",
      "blocks",
      "ic50",
      "ki",
    ],
  },
  binds: {
    type: "relation",
    tokens: [
      "binds",
      "bind",
      "binds to",
      "binding",
      "spr binding",
      "kd binding",
      "engages",
      "target engagement",
    ],
  },
  promotes: {
    type: "relation",
    tokens: ["promotes", "activates", "upregulates", "enhances", "stimulates"],
  },
  reduces: {
    type: "relation",
    tokens: [
      "reduces",
      "decrease",
      "lowers",
      "attenuates",
      "deprioritizes",
      "rejects",
      "rejected",
    ],
  },
  treats: {
    type: "relation",
    tokens: [
      "treats",
      "treatment",
      "therapeutic use",
      "advanced to in-vivo",
      "approved for in-vivo",
      "in-vivo pk study",
    ],
  },
  tested_in: {
    type: "relation",
    tokens: [
      "tested in",
      "profiled in",
      "measured in",
      "assayed in",
      "evaluated in",
      "run in",
      "screened in",
    ],
  },
  predicted_by: {
    type: "relation",
    tokens: [
      "predicted by",
      "predicted using",
      "modeled by",
      "scored by",
      "docked with",
      "forecast by",
      "estimated by",
    ],
  },
  belongs_to_chemotype: {
    type: "relation",
    tokens: [
      "belongs to chemotype",
      "classified as",
      "scaffold class",
      "chemotype membership",
      "series membership",
      "belongs to series",
    ],
  },
  routed_to_tier: {
    type: "relation",
    tokens: [
      "routed to tier",
      "assigned to tier",
      "advanced to tier",
      "routing decision",
      "approved for synthesis",
      "returned for optimization",
      "deprioritized",
    ],
  },
  supersedes: {
    type: "relation",
    tokens: [
      "supersedes",
      "replaces",
      "sar progression from",
      "evolved from",
      "next generation of",
      "improves upon",
    ],
  },
  has_structural_context: {
    type: "relation",
    tokens: [
      "has structural context",
      "adopts conformation",
      "binding site",
      "docked against",
      "structural binding mode",
      "pocket context",
    ],
  },
  potency_value: {
    type: "feature",
    tokens: [
      "ic50",
      "ki",
      "pic50",
      "pki",
      "half-maximal inhibitory concentration",
      "inhibitory constant",
      "potency value",
      "enzymatic potency",
      "cellular potency",
      "nm potency",
      "µm potency",
    ],
  },
  admet_property: {
    type: "feature",
    tokens: [
      "admet",
      "adme",
      "metabolic stability",
      "hlm t1/2",
      "microsomal stability",
      "cyp inhibition",
      "cyp3a4",
      "cyp2d6",
      "solubility",
      "aqueous solubility",
      "permeability",
      "caco-2",
      "efflux ratio",
      "bioavailability",
      "clearance",
      "half-life",
      "plasma protein binding",
      "herg",
      "toxicity flag",
    ],
  },
  selectivity: {
    type: "feature",
    tokens: [
      "selectivity",
      "selectivity ratio",
      "selectivity fold",
      "selective over",
      "counter-target selectivity",
      "off-target activity",
      "panel selectivity",
      "shp2 vs ptp1b",
      "kinase selectivity",
      "phosphatase selectivity",
    ],
  },
  biophysical_measurement: {
    type: "feature",
    tokens: [
      "kd",
      "spr kd",
      "surface plasmon resonance",
      "spr",
      "delta tm",
      "thermal shift",
      "dsf",
      "binding affinity",
      "residence time",
      "kon",
      "koff",
      "target engagement",
      "biophysical confirmation",
    ],
  },
  sar_finding: {
    type: "feature",
    tokens: [
      "sar",
      "structure-activity relationship",
      "sar trend",
      "sar analysis",
      "sar progression",
      "substituent effect",
      "r-group variation",
      "matched molecular pair",
      "mmp",
      "sar cliff",
      "activity cliff",
      "key pharmacophore",
      "critical interaction",
      "tolerated substitution",
      "detrimental substitution",
    ],
  },
  synthesis_route: {
    type: "feature",
    tokens: [
      "synthesis",
      "synthetic route",
      "synthetic scheme",
      "reaction step",
      "yield",
      "synthetic accessibility",
      "sa score",
      "retrosynthesis",
      "building block",
      "coupling reaction",
      "palladium coupling",
      "buchwald",
      "suzuki",
      "reductive amination",
      "protecting group",
      "intermediate",
      "final compound",
    ],
  },
  pk_property: {
    type: "feature",
    tokens: [
      "pharmacokinetics",
      "pk",
      "in vivo pk",
      "oral bioavailability",
      "f%",
      "auc",
      "cmax",
      "t1/2",
      "half-life",
      "clearance",
      "cl",
      "volume of distribution",
      "vd",
      "plasma exposure",
      "rat pk",
      "mouse pk",
      "iv pk",
      "po pk",
      "pk study",
      "pk profile",
    ],
  },
  disease_indication: {
    type: "actor",
    tokens: [
      "cancer",
      "oncology",
      "tumor",
      "noonan syndrome",
      "leopard syndrome",
      "nsclc",
      "lung cancer",
      "leukemia",
      "solid tumor",
      "ras-driven cancer",
      "mapk pathway cancer",
      "shp2-driven malignancy",
      "indication",
      "disease indication",
      "therapeutic area",
    ],
  },
  potency_measurement: {
    type: "feature",
    tokens: [
      "ic50",
      "ki",
      "pic50",
      "pki",
      "half-maximal inhibitory concentration",
      "inhibitory constant",
      "enzymatic ic50",
      "cellular ic50",
      "nm ic50",
      "µm ic50",
      "potency measurement",
      "measured ic50",
      "measured ki",
    ],
  },
  admet_measurement: {
    type: "feature",
    tokens: [
      "admet",
      "adme",
      "hlm t1/2",
      "microsomal stability",
      "metabolic stability",
      "cyp inhibition",
      "cyp3a4",
      "cyp2d6",
      "solubility",
      "aqueous solubility",
      "kinetic solubility",
      "permeability",
      "caco-2 permeability",
      "efflux ratio",
      "herg",
      "plasma protein binding",
      "ppb",
      "toxicity flag",
      "clearance",
      "bioavailability",
    ],
  },
  series_membership: {
    type: "relation",
    tokens: [
      "belongs to series",
      "classified as",
      "scaffold class",
      "chemotype membership",
      "series membership",
      "belongs to chemotype",
      "member of",
      "part of series",
      "indazole series",
      "pyrazine series",
      "aminopyridine series",
    ],
  },
  target_engagement: {
    type: "relation",
    tokens: [
      "binds",
      "bind",
      "binds to",
      "binding",
      "spr binding",
      "kd binding",
      "engages",
      "target engagement",
      "occupies",
      "interacts with",
      "forms complex with",
    ],
  },
  admet_profile: {
    type: "feature",
    tokens: [
      "admet profile",
      "adme profile",
      "hlm t1/2",
      "microsomal stability",
      "metabolic stability",
      "cyp inhibition",
      "cyp3a4 inhibition",
      "cyp2d6 inhibition",
      "caco-2 permeability",
      "efflux ratio",
      "kinetic solubility",
      "aqueous solubility",
      "plasma protein binding",
      "ppb",
      "herg inhibition",
      "clearance",
      "in vitro clearance",
      "toxicity flag",
      "pampa",
    ],
  },
  physicochemical_property: {
    type: "feature",
    tokens: [
      "molecular weight",
      "mw",
      "clogp",
      "logp",
      "logd",
      "tpsa",
      "hbd",
      "hba",
      "hydrogen bond donor",
      "hydrogen bond acceptor",
      "rotatable bonds",
      "lipophilicity",
      "lipinski",
      "ro5",
      "rule of five",
      "mpo score",
      "fsp3",
      "aromatic rings",
      "pka",
    ],
  },
  docking_score: {
    type: "feature",
    tokens: [
      "docking score",
      "glide score",
      "glide gscore",
      "mmgbsa",
      "mm-gbsa",
      "mc-mmgbsa",
      "binding pose",
      "docked pose",
      "virtual screening score",
      "scoring function",
      "free energy of binding",
      "predicted binding energy",
      "dock score",
    ],
  },
  allosteric_mechanism: {
    type: "feature",
    tokens: [
      "allosteric",
      "allosteric inhibition",
      "allosteric site",
      "allosteric pocket",
      "tunnel site",
      "closed conformation",
      "open conformation",
      "autoinhibited",
      "sh2-ph interface",
      "sh2-domain",
      "n-sh2",
      "c-sh2",
      "ptp domain",
      "interdomain interface",
      "conformational change",
      "allosteric mechanism",
    ],
  },
} as const;

/** Stable name of the platform-wide singleton template row. */
export const DEFAULT_TEMPLATE_NAME = "default";
